name: Show Commits Workflow

on:
  push:
    branches:
      - main # Replace "main" with your branch name if different

jobs:
  show-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Show Commit Message
        run: echo "Commit: ${{ github.event.head_commit.message }}"
